### ISSUE TITLE
Error when running jenkins task without build parameters

### ISSUE THREAD

**Issue by cpdtaylor** [gomorpheus/morpheus-jenkins-plugin#1]
[RxCachedThreadScheduler-3] ERROR c.m.t.TaskService - executeLocalTask error: java.lang.IllegalArgumentException: Text must not be null or empty
2022-12-29_08:11:37.21685 'java.lang.IllegalArgumentException: Text must not be null or empty
2022-12-29_08:11:37.21685 at groovy.json.JsonSlurper.parseText(JsonSlurper.java:202)
2022-12-29_08:11:37.21686 at groovy.json.JsonSlurper$parseText.call(Unknown Source)
2022-12-29_08:11:37.21686 at com.morpheusdata.jenkins.JenkinsTaskService.executeTask(JenkinsTaskService.groovy:127)

**Comment by cpdtaylor** [comment]
Fixing in PR: https://github.com/gomorpheus/morpheus-jenkins-plugin/pull/2
